[tool.poetry]
name = "dystopian-investment"
version = "0.1.0"
description = ""
authors = ["Carlos Vecina <carlosvecinatebar@gmail.com>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
vectorbt = "^0.26.0"
python-dotenv = "^1.0.1"
nbformat = "^5.10.3"
pydantic = "^2.7.0"
rel = "^0.4.9.9"
psycopg2 = "^2.9.9"
vecs = "^0.4.3"
pyarrow = "^17.0.0"
supabase = "^2.5.3"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"
#websockets = "10"
kafka-python = "^2.0.2"
weaviate-client = "^4.6.0"

[tool.poetry.group.scrape.dependencies]
beautifulsoup4 = "*"
pandas = "*"
selenium = "*"
webdriver-manager = "*"
undetected-chromedriver = "*"


[tool.poetry.group.agents.dependencies]
langchain-openai = "^0.1.3"
langchainhub = "^0.1.15"
lightrag = "^0.1.0b6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
