[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Carlos Vecina <carlos.vecina@jobandtalent.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"
#polars = "^0.20.15"
#sqlmodel = "^0.0.16"
vectorbt = "^0.26.0"
#ipykernel = "^6.29.3"
alpaca-trade-api = "^3.2.0"
python-dotenv = "^1.0.1"
nbformat = "^5.10.3"
#pydantic = "^2.6.4"
websockets = "10"
kafka-python = "^2.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
