name: Dystopic Fund
description: A fund that invests in the future
manager: 
  personality:
    mood: optimistic
    risk_tolerance: 0.5
  seniority: !openai_client {}
  seniority_args:
    model: gpt-4o-mini
    temperature: 0.0
analyst:
  - personality:
      mood: optimistic
      risk_tolerance: 0.5
    seniority: !openai_client {}
    seniority_args:
      model: gpt-4o-mini
      temperature: 0.0
trader:
  personality:
    mood: optimistic
    risk_tolerance: 0.5
  seniority: !openai_client {}
  seniority_args:
    model: gpt-4o-mini
    temperature: 0.9

