name: Dystopic Fund
description: A fund that invests in a dystopic orwellian or huxleyan future
type: discussion
manager:
  personality:
    mood: optimistic
    risk_tolerance: 0.5
  seniority: !openai_client_traceable {}
  seniority_args:
    model: gpt-4o-mini
    temperature: 0.0
analyst:
  personality:
    mood: optimistic
    risk_tolerance: 0.5
  seniority: !openai_client_traceable {}
  seniority_args:
    model: gpt-4o-mini
    temperature: 0.0
trader:
  personality:
    mood: optimistic
    risk_tolerance: 0.5
  seniority: !openai_client_traceable {}
  seniority_args:
    model: gpt-4o-mini
    temperature: 0.9
